{ config, pkgs, ... }:

{

  boot = {
    kernelParams = [
      "acpi_enforce_resources=lax"
    ];
  };

  environment = {
    systemPackages = with pkgs; [
      nvme-cli
      lm_sensors
      hddtemp
    ];

    etc = {
      "sysconfig/lm_sensors".text = ''
        # Generated by sensors-detect on Sat Nov 21 18:37:56 2020
        # This file is sourced by /etc/init.d/lm_sensors and defines the modules to
        # be loaded/unloaded.
        #
        # The format of this file is a shell script that simply defines variables:
        # HWMON_MODULES for hardware monitoring driver modules, and optionally
        # BUS_MODULES for any required bus driver module (for example for I2C or SPI).

        HWMON_MODULES="nct6775"
      '';
    };
  };
}
